### ISSUE TITLE
Only possible to create two classification rules pointing to the same chain the first time you try

### ISSUE THREAD

**Issue by manuelbuil** [trozet/tacker#18]
I am experiencing that if I create two classification rules pointing to a chain, the first time I try it works. However, if I delete those and then I create them again, the second rule replaces the first one. In other words:

1 - I create rule 1 pointing to chain 1. Result: I see a flow created in table = 11 with the syntax of rule 1
2 - I create rule 2 pointing to chain 1. Result: The previous flow is removed and now I see a flow created in table = 11 with the syntax of rule 2

**Comment by trozet** [comment]
@manuelbuil will look into this bug.  When you created the classifier, did you specify the name of the classifier?  If so, were they 2 different names? I see how that could cause the first one to be overwritten.

**Comment by manuelbuil** [comment]
Hey Tim, yes, they have two different names red_http and red_ssh.
